assets:
  js:
    - bundles/itkaarhussecondtemplate/templates/aarhus/assets/fontawesome.js
  js_prod_assets:
    - bundles/itkaarhussecondtemplate/templates/aarhus/assets/fontawesome.js

modules:

apps:
