assets:
  js:
    - bundles/itkaarhussecondtemplate/templates/aarhus/assets/fontawesome.js
  js_prod_assets:
    - bundles/itkaarhussecondtemplate/templates/aarhus/assets/fontawesome.js

modules:
  aarhusSecondTemplates:
    files:
      - bundles/itkaarhussecondtemplate/apps/aarhusSecondTemplates/contact-picker.js

apps:
  ikApp:
    dependencies:
      - aarhusSecondTemplates
